In [ ]:
import pandas as pd
import numpy as np


df=pd.read_csv('Bike Riders Data.csv')

# **Initial Inspection**

In [ ]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,47EC0A7F82E65D52,classic_bike,2022-03-21 13:45:01,2022-03-21 13:51:18,Wabash Ave & Wacker Pl,TA1307000131,Kingsbury St & Kinzie St,KA1503000043,41.886875,-87.626030,41.889177,-87.638506,member
1,8494861979B0F477,electric_bike,2022-03-16 09:37:16,2022-03-16 09:43:34,Michigan Ave & Oak St,13042,Orleans St & Chestnut St (NEXT Apts),620,41.900998,-87.623752,41.898203,-87.637536,member
2,EFE527AF80B66109,classic_bike,2022-03-23 19:52:02,2022-03-23 19:54:48,Broadway & Berwyn Ave,13109,Broadway & Ridge Ave,15578,41.978353,-87.659753,41.984045,-87.660274,member
3,9F446FD9DEE3F389,classic_bike,2022-03-01 19:12:26,2022-03-01 19:22:14,Wabash Ave & Wacker Pl,TA1307000131,Franklin St & Jackson Blvd,TA1305000025,41.886875,-87.626030,41.877708,-87.635321,member
4,431128AD9AFFEDC0,classic_bike,2022-03-21 18:37:01,2022-03-21 19:19:11,DuSable Lake Shore Dr & North Blvd,LF-005,Loomis St & Jackson Blvd,13206,41.911722,-87.626804,41.877945,-87.662007,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
284037,E23BE3DB740BE3B4,docked_bike,2022-03-13 16:31:03,2022-03-13 16:39:32,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.900960,-87.623777,41.892278,-87.612043,casual
284038,15AF71F3220F2A75,docked_bike,2022-03-09 06:56:02,2022-03-09 07:42:14,Broadway & Barry Ave,13137,Ravenswood Ave & Berteau Ave,TA1309000018,41.937582,-87.644098,41.957921,-87.673567,casual
284039,9C4CE6CC19F8225B,electric_bike,2022-03-09 15:55:26,2022-03-09 16:08:54,NaN,NaN,Albany Ave & Montrose Ave,15621,41.940000,-87.710000,41.961041,-87.705866,member
284040,F4E136DEF696F3AE,electric_bike,2022-03-21 16:12:44,2022-03-21 16:18:24,NaN,NaN,Larrabee St & Division St,KA1504000079,41.910000,-87.650000,41.903486,-87.643353,member
284041,5AEC5F39AF711895,classic_bike,2022-03-03 18:13:40,2022-03-03 18:23:39,Clark St & Randolph St,TA1305000030,Streeter Dr & Grand Ave,13022,41.884576,-87.631890,41.892278,-87.612043,member

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,47EC0A7F82E65D52,classic_bike,2022-03-21 13:45:01,2022-03-21 13:51:18,Wabash Ave & Wacker Pl,TA1307000131,Kingsbury St & Kinzie St,KA1503000043,41.886875,-87.626030,41.889177,-87.638506,member
1,8494861979B0F477,electric_bike,2022-03-16 09:37:16,2022-03-16 09:43:34,Michigan Ave & Oak St,13042,Orleans St & Chestnut St (NEXT Apts),620,41.900998,-87.623752,41.898203,-87.637536,member
2,EFE527AF80B66109,classic_bike,2022-03-23 19:52:02,2022-03-23 19:54:48,Broadway & Berwyn Ave,13109,Broadway & Ridge Ave,15578,41.978353,-87.659753,41.984045,-87.660274,member
3,9F446FD9DEE3F389,classic_bike,2022-03-01 19:12:26,2022-03-01 19:22:14,Wabash Ave & Wacker Pl,TA1307000131,Franklin St & Jackson Blvd,TA1305000025,41.886875,-87.626030,41.877708,-87.635321,member
4,431128AD9AFFEDC0,classic_bike,2022-03-21 18:37:01,2022-03-21 19:19:11,DuSable Lake Shore Dr & North Blvd,LF-005,Loomis St & Jackson Blvd,13206,41.911722,-87.626804,41.877945,-87.662007,member

In [ ]:
df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
284037,E23BE3DB740BE3B4,docked_bike,2022-03-13 16:31:03,2022-03-13 16:39:32,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.900960,-87.623777,41.892278,-87.612043,casual
284038,15AF71F3220F2A75,docked_bike,2022-03-09 06:56:02,2022-03-09 07:42:14,Broadway & Barry Ave,13137,Ravenswood Ave & Berteau Ave,TA1309000018,41.937582,-87.644098,41.957921,-87.673567,casual
284039,9C4CE6CC19F8225B,electric_bike,2022-03-09 15:55:26,2022-03-09 16:08:54,NaN,NaN,Albany Ave & Montrose Ave,15621,41.940000,-87.710000,41.961041,-87.705866,member
284040,F4E136DEF696F3AE,electric_bike,2022-03-21 16:12:44,2022-03-21 16:18:24,NaN,NaN,Larrabee St & Division St,KA1504000079,41.910000,-87.650000,41.903486,-87.643353,member
284041,5AEC5F39AF711895,classic_bike,2022-03-03 18:13:40,2022-03-03 18:23:39,Clark St & Randolph St,TA1305000030,Streeter Dr & Grand Ave,13022,41.884576,-87.631890,41.892278,-87.612043,member

In [ ]:
df.shape

(284042, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284042 entries, 0 to 284041
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             284042 non-null  object
 1   rideable_type       284042 non-null  object
 2   started_at          284042 non-null  object
 3   ended_at            284042 non-null  object
 4   start_station_name  236796 non-null  object
 5   start_station_id    236796 non-null  object
 6   end_station_name    232885 non-null  object
 7   end_station_id      232885 non-null  object
 8   start_lat           284042 non-null  float64
 9   start_lng           284042 non-null  float64
 10  end_lat             283776 non-null  float64
 11  end_lng             283776 non-null  float64
 12  member_casual       284042 non-null  object
dtypes: float64(4), object(9)
memory usage: 28.2+ MB

In [ ]:
df.describe()

           start_lat      start_lng        end_lat        end_lng
count  284042.000000  284042.000000  283776.000000  283776.000000
mean       41.896696     -87.648145      41.896923     -87.648285
std         0.049271       0.032462       0.049377       0.032547
min        41.648501     -87.840000      41.640000     -87.840000
25%        41.879434     -87.663940      41.879472     -87.664020
50%        41.895649     -87.643302      41.895765     -87.643353
75%        41.925858     -87.628722      41.926277     -87.628722
max        42.070000     -87.520000      42.070000     -87.510000

In [ ]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [ ]:
df.sample(15)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
67224,E85D2ECF6DDC0D86,classic_bike,2022-03-28 16:53:36,2022-03-28 16:56:58,Sheffield Ave & Wellington Ave,TA1307000052,Broadway & Barry Ave,13137,41.936253,-87.652662,41.937582,-87.644098,member
55586,97194B156CDE7E7D,classic_bike,2022-03-31 18:32:50,2022-03-31 18:38:40,Sedgwick St & North Ave,TA1307000038,Halsted St & Clybourn Ave,331,41.911386,-87.638677,41.909668,-87.648128,member
7730,D9E67730F2D0E4A2,classic_bike,2022-03-28 12:56:10,2022-03-28 12:59:35,Broadway & Cornelia Ave,13278,Broadway & Belmont Ave,13277,41.945529,-87.646439,41.940106,-87.645451,member
151387,B02CB4AD335F7F13,electric_bike,2022-03-11 19:56:35,2022-03-11 19:59:38,Leavitt St & Armitage Ave,TA1309000029,Leavitt St & North Ave,TA1308000005,41.917822,-87.682422,41.910509,-87.682389,member
17971,E20C6419606FA8E1,classic_bike,2022-03-21 10:40:17,2022-03-21 10:45:44,Orleans St & Chestnut St (NEXT Apts),620,Wells St & Hubbard St,TA1307000151,41.898203,-87.637536,41.889906,-87.634266,member
274283,C239769FFE6B3504,electric_bike,2022-03-06 05:44:08,2022-03-06 05:56:26,NaN,NaN,NaN,NaN,41.890000,-87.690000,41.930000,-87.700000,casual
269709,2A11444477C6E911,electric_bike,2022-03-22 06:20:04,2022-03-22 06:51:02,NaN,NaN,NaN,NaN,41.920000,-87.720000,41.830000,-87.730000,member
10306,47DA1F7EB09B0A84,classic_bike,2022-03-04 08:09:13,2022-03-04 08:21:07,Clinton St & Jackson Blvd,638,Michigan Ave & Washington St,13001,41.878317,-87.640981,41.883984,-87.624684,member
119456,564032E6581C9A40,electric_bike,2022-03-08 17:47:11,2022-03-08 17:54:36,Clark St & Wrightwood Ave,TA1305000014,Southport Ave & Belmont Ave,13229,41.929582,-87.643332,41.939478,-87.663748,casual
95525,5F51F2F805810342,classic_bike,2022-03-21 13:44:48,2022-03-21 14:01:49,Michigan Ave & Madison St,13036,Clinton St & Tilden St,13037,41.882134,-87.625125,41.875885,-87.640795,casual
162916,4F32C7CC5D856623,electric_bike,2022-03-17 20:28:59,2022-03-17 20:38:58,Kingsbury St & Kinzie St,KA1503000043,Ashland Ave & Augusta Blvd,13248,41.889203,-87.638476,41.899643,-87.667700,casual
121880,22EC59511259BB46,classic_bike,2022-03-22 18:54:18,2022-03-22 19:10:34,Larrabee St & Oak St,KA1504000116,Clark St & Wellington Ave,TA1307000136,41.900219,-87.642985,41.936497,-87.647539,member
69112,8D38DDD0B1054E2F,electric_bike,2022-03-02 17:00:45,2022-03-02 17:05:44,St. Clair St & Erie St,13016,Rush St & Cedar St,KA1504000133,41.894333,-87.622689,41.902309,-87.627691,member
89490,F60CC10B819E6D2F,electric_bike,2022-03-20 16:32:28,2022-03-20 16:57:11,Campbell Ave & Irving Park Rd,439,Troy St & North Ave,15653,41.950000,-87.690000,41.909769,-87.705280,casual
248793,E74C43FFA7D7DCD2,electric_bike,2022-03-05 17:49:19,2022-03-05 18:04:50,NaN,NaN,NaN,NaN,41.840000,-87.690000,41.890000,-87.700000,member

# Duplicated Rows handling

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
284037    False
284038    False
284039    False
284040    False
284041    False
Length: 284042, dtype: bool

# **Missing Value handling**

In [ ]:
df.isna()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
284037,False,False,False,False,False,False,False,False,False,False,False,False,False
284038,False,False,False,False,False,False,False,False,False,False,False,False,False
284039,False,False,False,False,True,True,False,False,False,False,False,False,False
284040,False,False,False,False,True,True,False,False,False,False,False,False,False
284041,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    47246
start_station_id      47246
end_station_name      51157
end_station_id        51157
start_lat                 0
start_lng                 0
end_lat                 266
end_lng                 266
member_casual             0
dtype: int64

In [ ]:
df[['end_lat','end_lng','start_station_name','start_station_id','end_station_name','end_station_id']].dtypes

end_lat               float64
end_lng               float64
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
dtype: object

In [ ]:
df.columns[df.isna().sum()>0]

Index(['start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'end_lat', 'end_lng'],
      dtype='object')

In [ ]:
df[df.columns[df.isna().sum()>0]].dtypes

start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
end_lat               float64
end_lng               float64
dtype: object

In [ ]:
null_cols = df.columns[df.isna().sum() > 0]
df[null_cols].dtypes

start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
end_lat               float64
end_lng               float64
dtype: object

In [ ]:
df[df.columns[df.isna().sum() > 0]]

,start_station_name,start_station_id,end_station_name,end_station_id,end_lat,end_lng
0,Wabash Ave & Wacker Pl,TA1307000131,Kingsbury St & Kinzie St,KA1503000043,41.889177,-87.638506
1,Michigan Ave & Oak St,13042,Orleans St & Chestnut St (NEXT Apts),620,41.898203,-87.637536
2,Broadway & Berwyn Ave,13109,Broadway & Ridge Ave,15578,41.984045,-87.660274
3,Wabash Ave & Wacker Pl,TA1307000131,Franklin St & Jackson Blvd,TA1305000025,41.877708,-87.635321
4,DuSable Lake Shore Dr & North Blvd,LF-005,Loomis St & Jackson Blvd,13206,41.877945,-87.662007
...,...,...,...,...,...,...
284037,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.892278,-87.612043
284038,Broadway & Barry Ave,13137,Ravenswood Ave & Berteau Ave,TA1309000018,41.957921,-87.673567
284039,NaN,NaN,Albany Ave & Montrose Ave,15621,41.961041,-87.705866
284040,NaN,NaN,Larrabee St & Division St,KA1504000079,41.903486,-87.643353
284041,Clark St & Randolph St,TA1305000030,Streeter Dr & Grand Ave,13022,41.892278,-87.612043

In [ ]:
df['start_station_name'].nunique()

843

In [ ]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,47EC0A7F82E65D52,classic_bike,2022-03-21 13:45:01,2022-03-21 13:51:18,Wabash Ave & Wacker Pl,TA1307000131,Kingsbury St & Kinzie St,KA1503000043,41.886875,-87.626030,41.889177,-87.638506,member
1,8494861979B0F477,electric_bike,2022-03-16 09:37:16,2022-03-16 09:43:34,Michigan Ave & Oak St,13042,Orleans St & Chestnut St (NEXT Apts),620,41.900998,-87.623752,41.898203,-87.637536,member
2,EFE527AF80B66109,classic_bike,2022-03-23 19:52:02,2022-03-23 19:54:48,Broadway & Berwyn Ave,13109,Broadway & Ridge Ave,15578,41.978353,-87.659753,41.984045,-87.660274,member
3,9F446FD9DEE3F389,classic_bike,2022-03-01 19:12:26,2022-03-01 19:22:14,Wabash Ave & Wacker Pl,TA1307000131,Franklin St & Jackson Blvd,TA1305000025,41.886875,-87.626030,41.877708,-87.635321,member
4,431128AD9AFFEDC0,classic_bike,2022-03-21 18:37:01,2022-03-21 19:19:11,DuSable Lake Shore Dr & North Blvd,LF-005,Loomis St & Jackson Blvd,13206,41.911722,-87.626804,41.877945,-87.662007,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
284037,E23BE3DB740BE3B4,docked_bike,2022-03-13 16:31:03,2022-03-13 16:39:32,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.900960,-87.623777,41.892278,-87.612043,casual
284038,15AF71F3220F2A75,docked_bike,2022-03-09 06:56:02,2022-03-09 07:42:14,Broadway & Barry Ave,13137,Ravenswood Ave & Berteau Ave,TA1309000018,41.937582,-87.644098,41.957921,-87.673567,casual
284039,9C4CE6CC19F8225B,electric_bike,2022-03-09 15:55:26,2022-03-09 16:08:54,NaN,NaN,Albany Ave & Montrose Ave,15621,41.940000,-87.710000,41.961041,-87.705866,member
284040,F4E136DEF696F3AE,electric_bike,2022-03-21 16:12:44,2022-03-21 16:18:24,NaN,NaN,Larrabee St & Division St,KA1504000079,41.910000,-87.650000,41.903486,-87.643353,member
284041,5AEC5F39AF711895,classic_bike,2022-03-03 18:13:40,2022-03-03 18:23:39,Clark St & Randolph St,TA1305000030,Streeter Dr & Grand Ave,13022,41.884576,-87.631890,41.892278,-87.612043,member

In [ ]:
df['start_lat'].nunique()

81725

In [ ]:
df['start_station_id'].nunique()

843

In [ ]:
df['start_station_name'].nunique()

843

In [ ]:
df['end_station_name'].nunique()

834

In [ ]:
df['end_station_id'].nunique()

834

In [ ]:
df.isna().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name    47246
start_station_id      47246
end_station_name      51157
end_station_id        51157
start_lat                 0
start_lng                 0
end_lat                 266
end_lng                 266
member_casual             0
dtype: int64

In [ ]:
df[['end_station_name', 'end_station_id']].isna().sum()

end_station_name    51157
end_station_id      51157
dtype: int64

## Handling start_station_name and start_station_id null values

In [ ]:
start_nan=df[df['start_station_id'].isna()]
start_nan.shape

(47246, 13)

In [ ]:
start_nan[['start_lat','start_lng']].isna().sum()

start_lat    0
start_lng    0
dtype: int64

In [ ]:
start_fill=df[df['start_station_id'].notna()]

In [ ]:
start_fill

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,47EC0A7F82E65D52,classic_bike,2022-03-21 13:45:01,2022-03-21 13:51:18,Wabash Ave & Wacker Pl,TA1307000131,Kingsbury St & Kinzie St,KA1503000043,41.886875,-87.626030,41.889177,-87.638506,member
1,8494861979B0F477,electric_bike,2022-03-16 09:37:16,2022-03-16 09:43:34,Michigan Ave & Oak St,13042,Orleans St & Chestnut St (NEXT Apts),620,41.900998,-87.623752,41.898203,-87.637536,member
2,EFE527AF80B66109,classic_bike,2022-03-23 19:52:02,2022-03-23 19:54:48,Broadway & Berwyn Ave,13109,Broadway & Ridge Ave,15578,41.978353,-87.659753,41.984045,-87.660274,member
3,9F446FD9DEE3F389,classic_bike,2022-03-01 19:12:26,2022-03-01 19:22:14,Wabash Ave & Wacker Pl,TA1307000131,Franklin St & Jackson Blvd,TA1305000025,41.886875,-87.626030,41.877708,-87.635321,member
4,431128AD9AFFEDC0,classic_bike,2022-03-21 18:37:01,2022-03-21 19:19:11,DuSable Lake Shore Dr & North Blvd,LF-005,Loomis St & Jackson Blvd,13206,41.911722,-87.626804,41.877945,-87.662007,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
284035,1CEE41690C73108B,classic_bike,2022-03-21 15:12:17,2022-03-21 15:23:01,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.900960,-87.623777,41.892278,-87.612043,member
284036,A2A6F07D3DF4D0D6,electric_bike,2022-03-09 20:29:48,2022-03-09 21:01:30,Sheridan Rd & Irving Park Rd,13063,Streeter Dr & Grand Ave,13022,41.954276,-87.654407,41.892278,-87.612043,casual
284037,E23BE3DB740BE3B4,docked_bike,2022-03-13 16:31:03,2022-03-13 16:39:32,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.900960,-87.623777,41.892278,-87.612043,casual
284038,15AF71F3220F2A75,docked_bike,2022-03-09 06:56:02,2022-03-09 07:42:14,Broadway & Barry Ave,13137,Ravenswood Ave & Berteau Ave,TA1309000018,41.937582,-87.644098,41.957921,-87.673567,casual
284041,5AEC5F39AF711895,classic_bike,2022-03-03 18:13:40,2022-03-03 18:23:39,Clark St & Randolph St,TA1305000030,Streeter Dr & Grand Ave,13022,41.884576,-87.631890,41.892278,-87.612043,member

In [ ]:
start_fill['start_station_name'].nunique()

843

In [ ]:
start_ref=start_fill.groupby('start_station_name')[['start_lat','start_lng']].median()

In [ ]:
start_ref

                              start_lat  start_lng
start_station_name
2112 W Peterson Ave           41.991178 -87.683593
63rd St Beach                 41.780911 -87.576324
900 W Harrison St             41.874754 -87.649807
Aberdeen St & Jackson Blvd    41.877726 -87.654787
Aberdeen St & Monroe St       41.880419 -87.655519
...                                 ...        ...
Woodlawn Ave & 55th St        41.795264 -87.596471
Woodlawn Ave & 75th St        41.759169 -87.595771
Woodlawn Ave & Lake Park Ave  41.814093 -87.597005
Yates Blvd & 75th St          41.758768 -87.566440
Yates Blvd & 93rd St          41.726166 -87.566276

[843 rows x 2 columns]

In [ ]:
from scipy.spatial import cKDTree

In [ ]:
start_ref.values

array([[ 41.991178  , -87.683593  ],
       [ 41.78091096, -87.57632375],
       [ 41.874754  , -87.649807  ],
       ...,
       [ 41.81409271, -87.59700515],
       [ 41.758768  , -87.56644   ],
       [ 41.72616639, -87.56627619]])

In [ ]:
tree=cKDTree(start_ref.values)

In [ ]:
tree

In [ ]:
dist, idx=tree.query(start_nan[['start_lat','start_lng']].values)

In [ ]:
start_ref.index[idx]

Index(['LaSalle St & Illinois St', 'N Clark St & W Elm St',
       'LaSalle St & Illinois St', 'LaSalle St & Illinois St',
       'Damen Ave & Wabansia Ave', 'Hampden Ct & Diversey Ave',
       'Campbell Ave & North Ave', 'Washtenaw Ave & Ogden Ave',
       'Damen Ave & Wabansia Ave', 'Richmond St & Diversey Ave',
       ...
       'Damen Ave & Coulter St', 'Campbell Ave & North Ave',
       'Menard Ave & Division St', 'Campbell Ave & North Ave',
       'Clark St & Berwyn Ave', 'Damen Ave & Clybourn Ave',
       'Sedgwick St & North Ave', 'Western Ave & Gunnison St',
       'Albany Ave & Belmont Ave', 'Dayton St & North Ave'],
      dtype='object', name='start_station_name', length=47246)

In [ ]:
df.loc[df['start_station_name'].isna(), 'start_station_name'] = start_ref.index[idx]

In [ ]:
df['start_station_name'].isna().sum()

np.int64(0)

In [ ]:
df['start_station_name']

0                     Wabash Ave & Wacker Pl
1                      Michigan Ave & Oak St
2                      Broadway & Berwyn Ave
3                     Wabash Ave & Wacker Pl
4         DuSable Lake Shore Dr & North Blvd
                         ...
284037                 Michigan Ave & Oak St
284038                  Broadway & Barry Ave
284039              Albany Ave & Belmont Ave
284040                 Dayton St & North Ave
284041                Clark St & Randolph St
Name: start_station_name, Length: 284042, dtype: object

In [ ]:
# Step 1: Mapping banao — name se id
name_to_id = df.dropna(subset=['start_station_id']).drop_duplicates('start_station_name').set_index('start_station_name')['start_station_id']

# Step 2: Null IDs fill karo using mapping
df.loc[df['start_station_id'].isna(), 'start_station_id'] = df.loc[df['start_station_id'].isna(), 'start_station_name'].map(name_to_id)

In [ ]:
df.isna().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name        0
start_station_id          0
end_station_name      51157
end_station_id        51157
start_lat                 0
start_lng                 0
end_lat                 266
end_lng                 266
member_casual             0
dtype: int64

## Handling null values of end_station_name and end_station_id

In [ ]:
df=df.dropna(subset=['end_lat'])

In [ ]:
df.shape

(283776, 13)

In [ ]:
df.isna().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name        0
start_station_id          0
end_station_name      50891
end_station_id        50891
start_lat                 0
start_lng                 0
end_lat                   0
end_lng                   0
member_casual             0
dtype: int64

In [ ]:
end_fill=df[df['end_station_name'].notna()]

In [ ]:
end_fill.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [ ]:
end_ref=df.groupby('end_station_name')[['end_lat','end_lng']].median()

In [ ]:
end_ref

                                end_lat    end_lng
end_station_name
2112 W Peterson Ave           41.991178 -87.683593
63rd St Beach                 41.780911 -87.576324
900 W Harrison St             41.874754 -87.649807
Aberdeen St & Jackson Blvd    41.877726 -87.654787
Aberdeen St & Monroe St       41.880419 -87.655519
...                                 ...        ...
Woodlawn Ave & 55th St        41.795264 -87.596471
Woodlawn Ave & 75th St        41.759160 -87.595751
Woodlawn Ave & Lake Park Ave  41.814093 -87.597005
Yates Blvd & 75th St          41.758768 -87.566440
Yates Blvd & 93rd St          41.726166 -87.566276

[834 rows x 2 columns]

In [ ]:
end_tree=cKDTree(end_ref.values)

In [ ]:
end_nan=df[df['end_station_name'].isna()]

In [ ]:
dist2, idx2 = end_tree.query(end_nan[['end_lat', 'end_lng']].values)

In [ ]:
df.loc[df['end_station_name'].isna(), 'end_station_name'] = end_ref.index[idx2]

In [ ]:
end_name_to_id = df.dropna(subset=['end_station_id']).drop_duplicates('end_station_name').set_index('end_station_name')['end_station_id']

df.loc[df['end_station_id'].isna(), 'end_station_id'] = df.loc[df['end_station_id'].isna(), 'end_station_name'].map(end_name_to_id)

In [ ]:
df.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [ ]:
df.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [ ]:
df.to_csv('cleaned_bike_data.csv', index=False)